### ISSUE TITLE
Is is possible to use purescript-routing?

### ISSUE THREAD

**Issue by denibertovic** [vladciobanu/purescript-halogen-example#5]
I'm curious why you haven't used [purescript-routing](https://github.com/slamdata/purescript-routing) for this example and have chosen to write your own router?

**Comment by eviefp** [comment]
The main reason is I wanted to showcase more of `Halogen` and using a `Free` monad  without going into other libraries too much.

Another reason is `purescript-routing` uses the location hash, whereas this repository is not (see the example; when navigating between routes there is no #hash at the end of the URL). Just wanted to show a very simple alternative.

It should be pretty easy to incorporate it though, just a matter of pushing the route from `matchesAff` to the `driver.query` inside `main`. I could create an alternate `Main` (or a branch or a fork or something) to demonstrate it if you can't get it working yourself.

**Comment by denibertovic** [comment]
@vladciobanu thanks for the detailed explanation. I'll see if I can get it working in a branch.

**Comment by eviefp** [comment]
There are a few other changes you'll probably want to make once you get that working:
- interpreting the `Navigate` command should change the hash instead of signaling to main (see [here](https://localhost/v6/Content/index.html#/adminapp/))
- some of the navigation buttons inside the components can be replaced by simple `a href`s with the appropriate hashtag
